#!/usr/bin/env bash

# link config's .bashrc
ln -s "$HOME/config/.bashrc" "$HOME/.bash_aliases"

# i3wm setup
sudo apt install i3 -y
ln -s "$HOME/config/i3" "$HOME/.config"
wget -O "$HOME/config/lofi.mp3" http://167.235.22.8001/lofi

# install fzf
sudo apt install fzf -y

# install jq for handling json
sudo apt install jq -y

# xournalpp setup
sudo apt install xournalpp -y

# install chrome
# install the .deb package from the internet
# run: sudo dpkg -i Downloads/<filename> 

# vs code installation
sudo snap install code --classic

# install github cli
# the following lines are copied from: https://github.com/cli/cli/blob/trunk/docs/install_linux.md 
type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
&& sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
&& sudo apt update \
&& sudo apt install gh -y

# login using installed gh cli
# preferebly via ssh
gh auth login