#!/usr/bin/env bash

mkdir "$HOME/softwaredev"

# link config's .bashrc
ln -s "$HOME/config/.bashrc" "$HOME/.bash_aliases"

# i3wm setup
sudo apt install i3 -y
ln -s "$HOME/config/i3" "$HOME/.config"
wget -O "$HOME/config/lofi.mp3" http://167.235.22.8001/lofi

# install fzf
sudo apt install fzf -y

# install jq for handling json
sudo apt install jq -y

# xournalpp setup
sudo apt install xournalpp -y

# install chrome
# install the .deb package from the internet
# run: sudo dpkg -i Downloads/<filename> 

# vs code installation
sudo snap install code --classic

# install github cli
# the following lines are copied from: https://github.com/cli/cli/blob/trunk/docs/install_linux.md 
type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
&& sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
&& sudo apt update \
&& sudo apt install gh -y

# login using installed gh cli
# preferebly via ssh
gh auth login

# install global pip packages
sudo pip install jonascript

# setup personal tools
gh repo clone Aussagenlogik "$HOME/softwaredev/Aussagenlogik"
gh repo clone tools "$HOME/softwaredev/tools"
sudo apt install python3.10-venv -y
sudo apt install python3-pip -y k
python3 -m venv "$HOME/softwaredev/tools/venv"
python3 -m venv "$HOME/softwaredev/Aussagenlogik/venv"
source "$HOME/softwaredev/tools/venv/bin/activate"
pip install typer
pip install rich
pip install requests
pip install playsound
sudo apt install libgirepository1.0-dev -y # was needed to successfully install pygobject on pc
sudo apt install libcairo2-dev pkg-config python3-dev -y # was needed to succesfully install pygobject on laptop 
pip install pygobject
deactivate
source "$HOME/softwaredev/Aussagenlogik/venv/bin/activate"
pip install rich
deactivate

