#!/usr/bin/env bash

selected=($(gh repo list --limit 1000 | fzf))
name="${selected[0]}"
parts=(${name//// })
if test -n "$1"; then
    gh repo clone "$name" "$HOME/softwaredev/$1"
    cd "$HOME/softwaredev/$1"
else
    gh repo clone "$name" "$HOME/softwaredev/${parts[1]}"
    cd "$HOME/softwaredev/${parts[1]}"
fi