#!/usr/bin/env bash

values=$(i3-msg -t get_workspaces)
if [[ "$values" == *"\"$1\""* ]]; then
    i3-msg workspace "\"$1\""
else
    if [[ "$2" == "--browser" ]]; then
        i3-msg workspace "\"$1\""
        i3-msg "exec google-chrome $3 --new-window"
    else
        if test -n "$2"; then
            cd "$2"
        else
            cd ~
        fi
        i3-msg workspace "\"$1\""
        i3-msg exec i3-sensible-terminal       
    fi
fi