#!/usr/bin/env python3

import sys
from jonascript import cmd, WINDOW

direction: str = sys.argv[1]
is_fullscreen = "_NET_WM_STATE_FULLSCREEN" in cmd(f"xprop -id {WINDOW} | grep '_NET_WM_STATE(ATOM)'").data
if is_fullscreen:
    cmd("i3 fullscreen toggle")
cmd(f"i3 focus {direction}")
if is_fullscreen:
    cmd("i3 fullscreen toggle")

