#!/usr/bin/env bash

name="$(basename $PWD)"
if [ "$1" != "." ]; then
    name="$1"
fi
git init
git branch -M master
git add .
git commit -m "first commit"
gh repo create "$name" "--$2" --source=. --push

