#!/usr/bin/env bash

filepath="$(readlink -f $1)"
pdfpath=""
template=""
numberOfPages=""
page_width=""
page_height=""
if [ "$2" == "latest" ]; then
    latest=$(ls -t "$HOME/Downloads" | head -n 1)
    pdfpath="$HOME/Downloads/$latest"
elif [[ "$2" == *".pdf" ]]; then
    pdfpath="$(readlink -f "$2")"
elif test -n "$2"; then
    template="$2"
fi
if test -n "$3"; then
    template="$3"
fi
if test -n "$pdfpath"; then
    mkdir "$filepath"
    cd "$filepath"
    filepath="annotations.xopp"
    cp "$pdfpath" "annotations.xopp.bg.pdf"
    numberOfPages=$(pdfinfo "$pdfpath" | grep 'Pages:' | awk '{print $2}')
    page_width=$(pdfinfo "$pdfpath" | grep 'Page size:' | awk '{print $3}')
    page_height=$(pdfinfo "$pdfpath" | grep 'Page size:' | awk '{print $5}')
fi
if test -e "$filepath" && test -z "$pdfpath"; then
    if test -d "$filepath"; then
        i3-msg "exec xournalpp '$filepath/annotations.xopp'"
    else
        i3-msg "exec xournalpp '$filepath'"
    fi
else
    python3 "$HOME/config/scripts/create-xopp.py" "$filepath" "$pdfpath" "$template" "$numberOfPages" "$page_width" "$page_height"
    i3-msg "exec xournalpp '$filepath'"
fi
wffs && i3 fullscreen toggle