#!/usr/bin/env bash

pdfpath=""
template=""
numberOfPages=""
page_width=""
page_height=""
if [ "$2" == "latest" ]; then
    latest=$(ls -t "$HOME/Downloads" | head -n 1)
    pdfpath="$HOME/Downloads/$latest"
elif [[ "$2" == *".pdf" ]]; then
    pdfpath="$(readlink -f "$2")"
elif test -n "$2"; then
    template="$2"
fi
if test -n "$3"; then
    template="$3"
fi
if test -n "$pdfpath"; then
    numberOfPages=$(pdfinfo "$pdfpath" | grep 'Pages:' | awk '{print $2}')
    page_width=$(pdfinfo "$pdfpath" | grep 'Page size:' | awk '{print $3}')
    page_height=$(pdfinfo "$pdfpath" | grep 'Page size:' | awk '{print $5}')
fi
if test -e "$1" && test -z "$pdfpath"; then
    xournalpp "$1" &
else
    python3 "$HOME/config/scripts/create-xopp.py" "$1" "$pdfpath" "$template" "$numberOfPages" "$page_width" "$page_height"
    xournalpp "$1" &
fi
sleep 0.5
i3 fullscreen toggle
